---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:*
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.0.1
  values:
    image:
      tag: v0.7.0
